'use server';
/**
 * @fileOverview An AI agent for sales and inventory analysis.
 *
 * - analyzeSalesAndInventory - A function that handles the sales and inventory analysis process.
 * - SalesAndInventoryAnalysisInput - The input type for the analyzeSalesAndInventory function.
 * - SalesAndInventoryAnalysisOutput - The return type for the analyzeSalesAndInventory function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SalesAndInventoryAnalysisInputSchema = z.object({
  sales: z.array(
    z.object({
      id: z.number(),
      date: z.string(),
      items: z.array(
        z.object({
          productId: z.number(),
          name: z.string(),
          priceVES: z.number(),
          priceUSD: z.number(),
          quantity: z.number(),
        })
      ),
      subtotal: z.number(),
      iva: z.number(),
      igtf: z.number(),
      total: z.number(),
      method: z.string(),
      cashier: z.string(),
      customerName: z.string(),
    })
  ).describe('Array of sales records.'),
  products: z.array(
    z.object({
      id: z.number(),
      code: z.string(),
      name: z.string(),
      description: z.string().optional(),
      categoryId: z.number(),
      priceVES: z.number(),
      priceUSD: z.number().optional(),
      stock: z.number(),
      minStock: z.number(),
      unit: z.string(),
      active: z.boolean(),
    })
  ).describe('Array of product inventory records.'),
  categories: z.array(
    z.object({
      id: z.number(),
      name: z.string(),
      description: z.string().optional(),
    })
  ).describe('Array of product categories.'),
  config: z.object({
    businessName: z.string(),
    rif: z.string(),
    address: z.string(),
    phone: z.string(),
    exchangeRate: z.number(),
    ivaRate: z.number(),
    igtfRate: z.number(),
    currency: z.string(),
  }).describe('Business configuration settings.'),
});
export type SalesAndInventoryAnalysisInput = z.infer<typeof SalesAndInventoryAnalysisInputSchema>;

const SalesAndInventoryAnalysisOutputSchema = z.object({
  executiveSummary: z.string().describe('A high-level executive summary of business performance.'),
  performanceInsights: z.object({
    totalSalesPeriod: z.string().describe('Total sales amount for the analyzed period.'),
    topSellingProducts: z.array(z.object({
      name: z.string().describe('Name of the product.'),
      totalRevenue: z.number().describe('Total revenue generated by this product.'),
      quantitySold: z.number().describe('Total quantity of this product sold.'),
    })).describe('List of best-selling products.'),
    lowStockProducts: z.array(z.object({
      name: z.string().describe('Name of the product.'),
      stock: z.number().describe('Current stock level.'),
      minStock: z.number().describe('Minimum required stock level.'),
    })).describe('List of products with stock at or below minimum levels.'),
    salesTrends: z.string().describe('Analysis of sales trends (e.g., growth, seasonality).'),
  }).describe('Detailed insights into sales and product performance.'),
  inventoryRecommendations: z.array(z.string()).describe('Actionable recommendations for inventory optimization.'),
  salesStrategyRecommendations: z.array(z.string()).describe('Actionable recommendations for improving sales strategies.'),
}).describe('Analysis and recommendations based on sales and inventory data.');
export type SalesAndInventoryAnalysisOutput = z.infer<typeof SalesAndInventoryAnalysisOutputSchema>;

export async function analyzeSalesAndInventory(
  input: SalesAndInventoryAnalysisInput
): Promise<SalesAndInventoryAnalysisOutput> {
  return salesAndInventoryAnalysisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'salesAndInventoryAnalysisPrompt',
  input: { schema: SalesAndInventoryAnalysisInputSchema },
  output: { schema: SalesAndInventoryAnalysisOutputSchema },
  prompt: `You are a highly skilled business analyst specializing in retail and inventory management.
Your task is to analyze the provided sales and product data for the business named '{{{config.businessName}}}'.
Generate a comprehensive executive summary, detailed performance insights, and actionable recommendations for inventory and sales strategies.

Here is the raw data:

Sales Data: {{{json sales}}}
Products Data: {{{json products}}}
Categories Data: {{{json categories}}}
Business Configuration: {{{json config}}}

Based on this data, provide the following:
1.  **executiveSummary**: A concise, high-level overview of the business's overall performance during the period covered by the sales data.
2.  **performanceInsights**: Detailed analysis including:
    *   'totalSalesPeriod': The total sales revenue (in VES) for the entire period covered by the sales data.
    *   'topSellingProducts': Identify the top 3-5 best-selling products by total revenue and quantity sold.
    *   'lowStockProducts': List all products that are currently at or below their minimum stock level.
    *   'salesTrends': Describe any noticeable sales trends, such as growth, decline, or products with significant changes in sales volume.
3.  **inventoryRecommendations**: Specific recommendations to optimize inventory. Consider aspects like reordering, managing slow-moving items, and adjusting minimum stock levels.
4.  **salesStrategyRecommendations**: Specific recommendations to improve sales performance. Consider aspects like promotions for certain products, customer targeting, or merchandising.

Ensure your output is structured as a JSON object strictly following the provided output schema. All numerical values for currency should be represented as numbers, not formatted strings.`,
});

const salesAndInventoryAnalysisFlow = ai.defineFlow(
  {
    name: 'salesAndInventoryAnalysisFlow',
    inputSchema: SalesAndInventoryAnalysisInputSchema,
    outputSchema: SalesAndInventoryAnalysisOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
